export const TYPES = {
    RESET: 'RESET',
    UPDATE_STATUS: 'UPDATE-STATUS',
    COUNTING: 'COUNTING',
    FLIP: 'FLIP',
    FLIPS: 'FLIPS',
    DECREASE_MATCH: 'DECREASE-MATCH',
    TOGGLE_MODAL: 'TOGGLE-MODAL',
    TOGGLE_RANK: 'TOGGLE-RANK'
};

export const USERS = {
    INIT: 'USERS-INIT',
    ADDED: 'USERS-ADD',
    REMOVED: 'USERS-REMOVE',
    UPDATED: 'USERS-UPDATED'
};

export const USER = {
    NAME_REQUIRED: 'USER-NAME-REQUIRED',
    NAME_CHANGE: 'USER-NAME-CHANGE',
    INIT: 'USER-INIT',
    UPDATED: 'USER-UPDATED',
};
