
export const TYPES = {
    RESET: 'RESET',
    UPDATE_STATUS: 'UPDATE-STATUS',
    COUNTING: 'COUNTING',
    UPDATE_HIGHESTSPEED: 'UPDATE-HIGHESTSPEED',
    FLIP: 'FLIP',
    FLIPS: 'FLIPS',
    DECREASE_MATCH: 'DECREASE-MATCH',
    TOGGLE_MODAL: 'TOGGLE-MODAL'
};

export const USER = {
    NAME_REQUIRED: 'USER-NAME-REQUIRED',
    NAME_CHANGE: 'USER-NAME-CHANGE',
    INIT: 'USERNAME-INIT',
    ADDED: 'USERNAME-ADDED',
    CREATED: 'USERNAME-CREATED',
    UPDATED: 'USERNAME-UPDATED',
};
